version: '3'
services:
  server:
    container_name: 'perspective_server'
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes: 
      - .:/usr/src/app/
    command: yarn start:server:watch
    ports:
      - 5000:5000
  
  db:
    container_name: 'perspective_db'
    image: 'neo4j:4.1.0'
    volumes: 
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment: 
      NEO4J_AUTH: 'none'
      
  web:
    container_name: 'perspective_web'
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: 
      - server
    links: 
      - server
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
